### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by rimus** [korolkoviktor/wdio-test#1]
1) pages/newpaste.js → need to optimize locators for dropdownMenuExpiration, dropdownMenuHighlght
2) Naming: please do not make different abbreviations/shorten forms of words. Please check whole hometask.
3) Code style → spaces between operators (like `=` etc).
4) pages/newpaste.js → Naming: NewPastePage.
5) pages/savedpaste.js → Naming: SavedPastePage. + Add `extend HomePage`.
6) tests/test.spec.js → split test suites into 2 describe-vlock or into 2 separate spec.js files. And please follow the rule «1 it() = 1 expect()».

**Comment by korolkoviktor** [comment]
Aliaksandr, accept invitation for access to my repository. please. 
I need this to add you as a pull-request reviewer.

**Comment by rimus** [comment]
Issues were fixed.
